name: GGORRI
version: '1.0-SNAPSHOT'
main: dev.o8o1o5.ggorri.GGORRI
api-version: '1.21'
commands:
  ggorri:
    description: GGORRI game commands.
    usage: /<command> [join|leave|start|stop]
    permission: ggorri.use
    permission-message: You don't have permission to use this command.
permissions:
  ggorri.use:
    description: Allows players to use GGORRI commands.
    default: true
  ggorri.admin:
    description: Allows administrators to use GGORRI admin commands (start, stop).
    default: op